services:
  db-server:
    image: mysql:8.0
    container_name: db-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: unow
      MYSQL_PASSWORD: holamundo
      MYSQL_DATABASE: project
    volumes:
      - mysql_data:/var/lib/mysql

  app-server:
    build:
      context: ./app-server
    container_name: app-server
    restart: always
    environment:
      TZ: America/Bogota
    ports:
      - "3001:80"
      - "2222:22"
    volumes:
     - project_code:/var/www/html
    depends_on:
      - db-server
    
  email-service:
    build:
      context: ./email-service 
    container_name: email-service
    restart: always
    ports:
      - "5000:5000"
    volumes:
     - project_email:/app

  website:
    build: 
      context: ./website 
    container_name: website
    restart: always
    ports:
      - "80:3000"
      - "2200:22"
    volumes:
     - project_website:/app
volumes:
  project_code:
  mysql_data:
  project_email:
  project_website: